import React, { useEffect, useState } from 'react'
import DetailData from './DetailData'
import axios from 'axios'
import { apiHeader, convertArrayToObject, daysDifference } from '../../../utils/Functions'
import { useSelector } from 'react-redux'

const ReturnTable = ({data, itemList}) => {


    const {uomObj} = useSelector(state => state.uoms)
    
 const orgConsignorDetails = [
    {
        title: "Consignor Regional Center Code",
        dataIndex: "crRegionalCenterCd"
    },
    {
        title: "Consignor Regional Center Name",
        dataIndex: "crRegionalCenterName"
    },
    {
        title: "Consignor Address",
        dataIndex: "crAddress"
    },
    {
        title: "Consignor Zipcode",
        dataIndex: "crZipcode"
    }
]
 const orgConsigneeDetails = [
    {
        title: "Consignee Regional Center Code",
        dataIndex: "ceRegionalCenterCd"
    },
    {
        title: "Consignee Regional Center Name",
        dataIndex: "ceRegionalCenterName"
    },
    {
        title: "Consignee Address",
        dataIndex: "ceAddress"
    },
    {
        title: "Consignee Zipcode",
        dataIndex: "ceZipcode"
    }
]

 const consumerDetails = [
    {
        title: "Consumer Name",
        dataIndex: "consumerName"
    },
    {
        title: "Contact No",
        dataIndex: "contactNo"
    }
]

const itemDetails = [
    {
        title: "Item Code",
        dataIndex: "itemCode"
    },
    {
        title: "Item Description",
        dataIndex: "itemDesc"
    },
    {
        title: "Uom Description",
        dataIndex: "uom",
        render: (uom) => uomObj[parseInt(uom)]
    },
]  

    const dataColumns = [
        {
            title: "Return Note No.",
            dataIndex: "processId"
        },
        {
            title: "Return Note Date",
            dataIndex: "returnNoteDt"
        },
        {
            title: "Issue Note No.",
            dataIndex: "processId"
        },
        {
            title: "Issue Note Date",
            dataIndex: "issueNoteDt"
        },
        {
            title: "Terms And Condition",
            dataIndex: "termsCondition"
        },
        {
            title: "Note",
            dataIndex: "note"
        },
        {
            title: "Generated by",
            dataIndex: "genName"
        },
        {
            title: "Generation Date",
            dataIndex: "genDate"
        },
        {
            title: "Returned / Submitted by",
            dataIndex: "approvedName"
        },
        {
            title: "Return / Submission Date",
            dataIndex: "approvedDate"
        },
        {
            title: "Consignor Regional Center Code",
            dataIndex: "regionalCenterCd"
        },
        {
            title: "Consignor Regional Center Name",
            dataIndex: "regionalCenterName"
        },
        {
            title: "Consignor Address",
            dataIndex: "address"
        },
        {
            title: "Consignor Zipcode",
            dataIndex: "zipcode"
        },
        ...consumerDetails

    ]

    const itemListColumns = [
        ...itemDetails,
        {
            title: "Return Quantity",
            dataIndex: "quantity"
        },
        {
            title: "Returned After No. Of Days",
            dataIndex: "requiredDays",
            render: (_, record) => daysDifference(data.issueNoteDt, data.genDate)
        },
        {
            title: "Condition Of Goods",
            dataIndex: "conditionOfGoods"
        },
        {
            title: "Remarks",
            dataIndex: "remarks"
        },
    ]
  return (
    <DetailData dataColumn={dataColumns}  itemListColumn={itemListColumns} data={data} itemList={itemList}/>
  )
}

export default ReturnTable
